# Generated by Django 3.2.21 on 2023-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('genre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_year', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('HORROR', 'Active'), ('SCI-FI', 'sci-fi'), ('ROMANCE', 'romance'), ('DRAMA', 'drama'), ('COMEDY', 'comedy'), ('ACTION', 'action')], max_length=200)),
            ],
            options={
                'ordering': ('-title',),
            },
        ),
    ]
