# Generated by Django 3.2.21 on 2023-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('-title',), 'verbose_name_plural': 'Movies'},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('HORROR', 'horror'), ('SCI-FI', 'sci-fi'), ('ROMANCE', 'romance'), ('DRAMA', 'drama'), ('COMEDY', 'comedy'), ('ACTION', 'action')], max_length=200),
        ),
    ]
